`timescale 1ns / 1ps
module fir_filter(
    input clk,
    input signed [7:0] x,
    output reg signed [15:0] y
);

reg signed [7:0] delay1, delay2, delay3;

always @(posedge clk)
begin

    // Shift previous samples
    delay3 <= delay2;
    delay2 <= delay1;
    delay1 <= x;

    // FIR Equation
    y <= (1*x) + (2*delay1) + (3*delay2) + (4*delay3);

end

endmodule

//The fir_filter.v file contains the Verilog code for a simple FIR (Finite Impulse Response) digital filter design.
//The design uses a clock signal (clk), signed 8-bit input signal (x), and signed 16-bit output signal (y).
//The registers delay1, delay2, and delay3 are used to store previous input samples for filtering operation.
//The always @(posedge clk) block indicates synchronous operation controlled by the positive edge of the clock signal
//During every clock cycle, previous input samples are shifted through delay registers.
//delay1 stores the current input sample, delay2 stores the previous sample, and delay3 stores older samples.
//The shifting operation helps the filter maintain past input values required for FIR filtering.
//The FIR equation performs weighted multiplication and addition of current and previous input samples.
//The expression y <= (1*x) + (2*delay1) + (3*delay2) + (4*delay3) calculates the filtered output value.
//Different coefficients (1, 2, 3, and 4) are used to give different weights to input samples during filtering.
//The output y stores the final filtered result generated by the FIR filter.
//The design demonstrates the basic working principle of a synchronous FIR digital filter using Verilog HDL.
